### ISSUE TITLE
Add difficulty adjustments for going deeper in a dungeon

### ISSUE THREAD

**Issue by pagewin** [dmr-capstone/dmr-capstone#123]
- [x] Figure out formulas that scale appropriately (a flat multiplier works but is dumb and boring). You need separate ones for separate enemy statistics.
- [x] Find a way to track the difficulty increases across scene loads
- [x] Update enemy statistics when spawning them based on the difficulty

I made a singleton `SeamlessMusicPlayer` that would do the job for keeping a persistent object, just rename it to something less specific. You would attach the script to an object in the scene and have a variable in another script (keep it modular - the singleton script is used by something else so keep the difficulty logic elsewhere) that is publicly modifiable. In the `Delve.cs` script, which is called when the player goes down a level, you would update those variables used in the difficulty calculations.

Also, make sure to destroy the object in the `Escape.cs` script (same as the music player), or the difficulty will be "saved" even when you return to the hub.

In the `DungeonType` class, there are fields for each spawnable enemy for the base stats. You could also rip that stuff out and just read the variables from the prefabs, whichever you like.

**Comment by zalfenior** [comment]
Added floor tracker to state manager

**Comment by zalfenior** [comment]
Since i'll be messing with values anyway I can try this too

**Comment by pagewin** [comment]
@zalfenior I dug out some formulas I used for stat adjustment on a lame text RPG I did a couple of years ago. They might help, would need some adjustments on the constants maybe, also it was in C++

```cpp
float Actor::getStat(Stats st) {
	if ( st >= CURHP || st <= MAXMP) { // HP / MP
		return stats[st];
	} else {	// diminishing returns
		return stats[st] * exp(stats[st] / -128.0);
	}
}

// No I don't remember why I had to formulas that both appear to be exp gain
(( log(enemyLevel + 1) * sqrt(enemyLevel) * 32 )
        + randomRange(1, pow(enemyLevel, 2)) + 5)
        * expBonus

expGain = ceil( (log(enemyLevel)) * sqrt(enemyLevel) * 32 + randomRange(1, pow(enemyLevel, 2) + 5))
        * float((enemyLevel / (float) user -> getLevel()) )
```

**Comment by pagewin** [comment]
Caveat: did not modify speed or accuracy with this, but damage, health, points are scaled based on dungeon level
