### ISSUE TITLE
Strange Pause Menu Behavior

### ISSUE THREAD

**Issue by yhbautista** [dmr-capstone/dmr-capstone#169]
**Behavior**: There were a series of behaviors all related to this issue:

1. When you quit the game via the pause menu and head back to the home screen, the home screen shows PAUSED at the top.
2. If you do not fix the previous issue and reenter the game, the mouse stays un-captured and PAUSED remains at the top of the screen. This is fixed by showing and hiding the pause menu once, at which point the game captures the mouse again and the PAUSED at the top goes away.
3. If you show and hide the pause menu while in the main menu in order to fix issue number 1 above, the game captures the mouse. While it's still possible to select a graphics setting, it becomes impossible to choose to play or quit the executable. 
4. The previous issue is fixed by showing the pause menu and quitting as if you were in the game, at which point the mouse remains captured by the pause menu with PAUSED at the top of the screen. Unfortunately, attempting to enter the game again will lead you to an empty world--the hub will have disappeared. I'm not sure if this is an issue because I opened the pause menu while in the main menu, or because I "quit" the game while in the main menu (i.e. I don't know if it was caused by solution in 3 or in 4).

**Comment by pagewin** [comment]
(4) is because the player object is not destroyed at any point, so when you respawn in the hub, it's the last position of the player. If you quit from the dungeon, it's probably going to be outside the hub bounds. Player object needs to be destroyed on quit.
