### ISSUE TITLE
Strange Collision Box Behavior

### ISSUE THREAD

**Issue by yhbautista** [dmr-capstone/dmr-capstone#170]
It may just be my terrible aim, but there seems to be a strange behavior on the *enemy* character collision boxes, at least when using the milk hose. If the character is too close to or phasing through an obstacle, then it becomes impossible to hit the character. This might need more investigation, though, and waiting until the enemy AI has been finished.

**Comment by pagewin** [comment]
Collisions act strangely with mesh colliders and sometimes bullets hit the player. Need to add manual shaped colliders to all objects and not allow the player's bullets to hit itself
