### ISSUE TITLE
Adjust enemy prefabs so that they have a white material

### ISSUE THREAD

**Issue by zalfenior** [dmr-capstone/dmr-capstone#191]
Change one of the base materials to white and remove the other prefab. This way we can have enemies that are multicolored without the red base ones all turning black

**Comment by pagewin** [comment]
Try to fix the crawler. The first material isn't the recolorable material, so they can't be recolored. Can you order them properly in the model?

**Comment by zalfenior** [comment]
I dont know for sure but I'll certainly try. Does the enemy generator go through a list of prefabs or are those linked in the inspector

**Comment by pagewin** [comment]
@zalfenior  linked in the inspector to the prefabs, so just update the prefabs and then double check that both Dungeon Types are not missing prefabs under the random enemies section (jn case unity decides the guid is gone)

**Comment by zalfenior** [comment]
@pagewin Sounds like a plan. When you get your stuff merged in I'll start on that. (after dinner obviously)
