### ISSUE TITLE
Final Report Section #7 Local and Global Impacts

### ISSUE THREAD

**Issue by zalfenior** [dmr-capstone/dmr-capstone#202]
Check yourself if you did your part
- [x] Zachary Maly
- [x] Tiff Horton
- [x] Yadira Bautista
- [x] Mark Turpen
- [x] William Lopez
- [ ] Eric Phillips

bluh

**Comment by zalfenior** [comment]
Did a paragraph or two, knocked out one of the bulletpoints

**Comment by pagewin** [comment]
Looks like enough meat in there. Requirement is 1 page, which we've filled out. Awaiting @yhbautista and @ericp275 if they have further input.
