### ISSUE TITLE
Final report 4.1 directory structure

### ISSUE THREAD

**Issue by pagewin** [dmr-capstone/dmr-capstone#228]
add image of directory structure OF SOURCE CODE ONLY, so just fiscal-shock/Assets/Scripts directory.

discuss the overall directory structure of source code
indicate which files were:
* blackbox reused from existing libraries or projects (identify the source)
    - ThirdParty dir
* adapted and modified from existing libraries or projects (identify the source)
    - Gaussian function
    - fps controls?
    - perhaps others
* ~~auto-generated (identify the tool)~~
    - we don't have auto generated source code
* written from scratch (most)

**Comment by zalfenior** [comment]
Got the image ready

**Comment by pagewin** [comment]
Completed by Zack and me
